#!/bin/bash

package_path() {
    echo packages/"$1"
}

validate_package_name() {
    local name=$1
    if [ "$name" == '' ] || [ ! -d "$(package_path "$name")" ]; then
        echo Please provide a validate package name.
        exit 1
    fi
}

validate() {
    validate_package_name "$1"
}

build() {
    yarn build
}

tag() {
    local name="$1"
    local version
    local menifest

    menifest=$(package_path "$name")/package.json
    version=$(jq -r '.version' "$menifest")
    echo tagging name="$name" menifest="$menifest" version="$version"
}

test() {
    echo testing
}

install() {
    echo installing
}

publish() {
    local package=$1
    validate "$package"
    tag "$package"
    echo Publishing "$package"
}

case $1 in
publish)
    publish "$2"
    ;;
*)
    echo nothing to do.
    exit 1
    ;;
esac
