// Generated by dts-bundle-generator v9.5.1

import { BuildOptions, Loader, Plugin } from 'esbuild';

export interface MinimaPlugin extends Omit<Plugin, "setup"> {
	setup?: Plugin["setup"];
	entry?: string[];
}
export type EsbuildOverrides = Omit<BuildOptions, "entryPoints" | "outdir" | "plugins" | "metafile" | "bundle" | "platform" | "format">;
export type Runtime = "node" | "bun";
export interface BaseConfig {
	entry: string[];
	run: boolean;
	exec: string;
	watch: boolean;
	clean: boolean;
	sourcemap: boolean;
	tsconfig: string;
	minify: boolean;
	check: boolean;
	reset: boolean;
	killSignal: NodeJS.Signals;
	import: string[];
	outdir: string;
	loader: Record<string, Loader>;
	target?: string;
	envFile?: string | string[];
	plugins?: MinimaPlugin[];
	esbuild?: EsbuildOverrides;
}
export type ConfigMode = "dev" | "build" | "start";
export interface ConfigEnv {
	mode: ConfigMode;
	dev: boolean;
}
export interface CliOption extends Partial<BaseConfig> {
	grace?: boolean;
	mode: ConfigMode;
}
export interface Config extends BaseConfig {
	external?: {
		include?: string[];
	};
}
export type ConfigFactory = (env: ConfigEnv) => Promise<Config>;
export declare function runtime(): Runtime;
export declare namespace runtime {
	var version: () => string;
	var detect: typeof detect;
	var bin: (rt?: Runtime) => string;
	var isNode: (bin: string) => boolean;
}
export declare function detect(): Runtime;
export declare namespace detect {
	var version: () => string | null;
}
export type PM = "bun" | "pnpm" | "yarn" | "npm";
export interface PMOptions {
	cwd?: string;
}
declare function isYarnBerry(cwd?: string): boolean;
declare function detect$1(cwd?: string): PM;
declare function getVersion(manager: PM): string | null;
declare const EXEC: Record<Exclude<PM, "bun">, string>;
declare function isInstalled(pkg: string): boolean;
declare function add(packages: string[], opts?: PMOptions & {
	dev?: boolean;
	skipInstalled?: boolean;
}): void;
declare function remove(packages: string[], opts?: PMOptions): void;
declare function install(opts?: PMOptions): void;
declare function run(script: string, args?: string[], opts?: PMOptions): void;
export declare function defineConfig(config: Partial<Config>): ConfigFactory;
export declare function defineConfig(config: (env: ConfigEnv) => Partial<Config>): ConfigFactory;

declare namespace pm {
	export { EXEC, PM, PMOptions, add, detect$1 as detect, getVersion, install, isInstalled, isYarnBerry, remove, run };
}

export {
	pm,
};

export {};
